require_relative 'consensus'

describe Consensus do
  let(:data) {File.read("rosalind_cons.txt")}

  let(:output) {"ATGCAACT
A: 5 1 0 0 5 5 0 0
C: 0 0 1 4 2 0 6 1
G: 1 1 6 3 0 1 0 0
T: 1 5 0 0 0 1 1 6"}

  it "returns a consesus string and profile matrix for a given set of DNA strings" do
    File.write('solution.txt', Consensus.for(data))
    expect(Consensus.for(data)).to eq output
  end

  it "processes input" do
    skip
    input = ">Rosaline_5636
 GGAGAACAGTGGCCTTTTACGTCGGAGAACTAGCCTCGCATCAGTGACTTTCTGGTTTCC
 CGGGATACGACCTGAAAACTGACGCTTGGAATCGAGGGGAAAAGACTCCCACCTGTGAGC
 TGAATCCCGAAGAAAAGACATCCATAGGACGTGTGCTTTCTAACCCAGGACATCCAACGG
 GCTGACCATGGGACTATTCAGATGCTTTTTTACTTCTCTTCGCCGTCATCGTTACCTTCC
 CAAGTTGTCGGGAGAAGATAACGTGACGCAAGTATTAGACATTTTATACGCTAGAGGGAC
 GCTAGCTTACAGGCCAAATCCCTCTCCGATGTGGGTACAGGCTTGTGCTGGGCACATGCG
 ATCCCGTGGTCGGGGTTTTGCCTTGTCGGATCTGCTCTAAGGTTCAGTGCGTATAACATC
 TCTATATATGATGAGCTACCGGAGCTCACACCATTTAATTGAGTGCTTACCTGAGTCTAG
 AATTGACTATCAGAGTATGGCGTTTCCCTTTGGCGTTGAGAGGAATTGTAGGTGGCAGTA
 TCGACGGATATTTAGACATGTGTGTGAAGCCAACCCGTGTTGTAGTAAAGAGTCCGTGCG
 TGGTCGATATGGACTCAAGCGCCGGCATTCACTACAAGGCCCGTGATGCGAAGCATAGTC
 GAAACATAGTATACAGGGGTATAGGATTCTACCGTTGTAAGGAACGATGCTAAGGACTTG
 AGGTAAGCTTAAGCTCCGGCTGAGGAGAAAGACCTATTATTGTCACAAATTTGAGGTCAA
 CCACCAAAAGGCTGCACTTTGCCAAGGGCGACTAGCGAGCTTTTTCACCGAGTATGGTCT
 GCGGTTCGCTTCACGATACGCCCGGCCAAGACCCTGGATGCCTAATTGAATGTAAGGCGA
 CCGGATGGGTTACCAACGCCCTAATGACGCGGATGGTGAGTGTCATTATCCGTGGCGTTC
 ATGAGT"
    expect(Consensus.process_input(input)).to eq 5
  end
end
